name: Stringtables.xml

on:
  push:
    branches:
       - main
    pull_request:


jobs:
  run_python:
    runs-on: ubuntu-latest
    permissions:
        contents: read
        issues: write
    steps:
      - name: Install Python packages
        run: |
          pip3 install wheel
          pip3 install setuptools
          pip3 install pygithub
          pip3 install pygithub3
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Update Translation issue
        if: github.repository == 'prisonerMO/iedd' && github.ref	== 'refs/heads/main' && ! contains(github.event.head_commit.message, '[ci skip]')
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 extras/tools/stringtableDeploy.py
